basic_app/urls.py
from django.conf.urls import url
from basic_app import views
from django.urls import path
# TEMPLATE TAGGING
app_name = 'basic_app'
urlpatterns = [
    path('relative/',views.relative, name = 'relative'),
    path('others/',views.others, name = 'others'),
]

learning_templates/urls.py
from django.contrib import admin
from django.urls import path
from basic_app import views
from django.urls import include, path

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls'))
]

basic_app/models.py
from django.db import models

# Create your models here.

basic_app/views.py
from django.shortcuts import render



def index(request):
    return render(request,'basic_app/index.html')


def others(request):
    return render(request,'basic_app/others.html')

def relative(request):
    return render(request,'basic_app/relative_url_templates.html')
# Create your views here.

templates/basic_app/basic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body>
    <div class='container'>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    
        <a class="navbar-brand" href="{% url 'index' %}">BRAND</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'admin:index' %}"> Admin </a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'basic_app:others'%}">Others</a>
            </li>
          </ul>
        </div>
    </nav>
    
    <div>
        {% block body_block %}
        {% endblock%}
    </div>
    </div>
</body>
</html>

templates/basic_app/index.html
<!DOCTYPE html>
{% extends 'basic_app/basic.html' %}
    {% block body_block %}
    <h1>Welcome to HomePage</h1>
    <h1>Well tags are really cool, i am loving it</h1>
    {% endblock body_block %}

templates/basic_app/others.html
<!DOCTYPE html>
{% extends 'basic_app/basic.html' %}
    {% block body_block %}
        <h1>Welcome to other Page</h1>
        <h2>Well i have done my forst cool inheritence</h2>
{% endblock%}

templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Welcome to relative url templates page</h1>
    <a href="{% url 'basic_app:others' %}">THE OTHER PAGE</a>
</body>
</html>